#!/bin/bash
# Instrucciones rápidas para desplegar en Vercel

echo "📦 Gestór de Colecciones - Deployment Helper"
echo "=============================================="
echo ""
echo "1. Asegúrate de tener todo commiteado:"
echo "   git add ."
echo "   git commit -m 'Preparar para Vercel'"
echo ""
echo "2. Sube a GitHub:"
echo "   git push origin main"
echo ""
echo "3. Ve a vercel.com y:"
echo "   - Clic en 'Add New Project'"
echo "   - Selecciona tu repositorio"
echo "   - ¡Vercel hará el resto automáticamente!"
echo ""
echo "4. Tu app estará disponible en:"
echo "   https://tu-proyecto.vercel.app"
echo ""
echo "⚠️  IMPORTANTE:"
echo "   Los datos se reinician en cada deploy"
echo "   Considera añadir una base de datos"
echo ""
